version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server"]

  init-redis:
    image: redis
    depends_on:
      - redis
    volumes:
      - ./init-redis.sh:/init-redis.sh
    command: ["/init-redis.sh"]